---
#Disk size config
sap_disk_size: "128.00 GB"
swap_disk_size: "40.00 GB"

#Logical volume size config
swap_lv_size: "30g"
usrsap_lv_size: "5g"
sap_lv_size: "20g"
sapmnt_lv_size: "20g"
saptrans_lv_size: "20g"
...
