---
#Disk size config
data_disk_size: "256.00 GB"
log_disk_size: "32.00 GB"
arch_disk_size: "64.00 GB"
sap_disk_size: "128.00 GB"
swap_disk_size: "32.00 GB"

#Logical volume size config
swap_lv_size: "30g"
db2software_lv_size: "5g"
db2_lv_size: "2g"
db2dump_lv_size: "5g"
sapdata1_lv_size: "25g"
sapdata2_lv_size: "25g"
sapdata3_lv_size: "25g"
sapdata4_lv_size: "25g"
saptmp1_lv_size: "5g"
saptmp2_lv_size: "5g"
saptmp3_lv_size: "5g"
saptmp4_lv_size: "5g"
log_lv_size: "25g"
archlog_lv_size: "50g"
usrsap_lv_size: "5g"
sap_lv_size: "20g"
sapmnt_lv_size: "20g"
saptrans_lv_size: "20g"
...